### ISSUE TITLE
add gatsby-source-s3

### ISSUE THREAD

**Issue by robinmetral** [gatsby-uc/plugins#122]
### Plugin Repository

https://github.com/robinmetral/gatsby-source-s3

### Plugin Package

https://www.npmjs.com/package/@robinmetral/gatsby-source-s3

### Plugin Description

tl;dr: the plugin pulls images from AWS S3 buckets at build time. It enables Gatsby to process them with sharp, while hosting the raw images off of GitHub—useful for image-heavy sites and blogs that don't use a CMS.

---

Extra context:

I didn't create the first ever `gatsby-source-s3`: [the first one](https://github.com/DSchau/gatsby-source-s3/) was made by DSchau, but it stopped being maintained long ago (last commit was in late 2019) and I created mine to fix existing issues with it. There's also jessestuart's [`gatsby-source-s3-image`](https://github.com/jessestuart/gatsby-source-s3-image), which was written in TypeScript but also stopped being maintained a few years ago (last commit excluding automatic dep updates was in late 2019).

So my version of `gatsby-source-s3` took aspects from these two unmaintained plugins and improved upon them.

Some key aspects:

- It supports pulling from multiple and/or private S3 buckets
- It's fully compatible with Gatsby v4 (recently updated)
- It has a nice e2e test suite (bootstraps a real Gatsby site pulling from real S3 buckets inside GitHub actions)
- TypeScript

### Further Details

I'm in the exact scenario that you're describing in this repo's README. I [initially asked](https://github.com/gatsbyjs/gatsby/discussions/34050) if the plugin could be moved to the core monorepo and was sent here.

**Comment by moonmeister** [comment]
Hello Robin! We'd love to host the plugin. Bellow are the steps for you and me. Since this is published under your user scope I'm not sure if that makes permissions different or if they're the same. It would be nice if @DSchau could give us access to the `gatsby-source-s3` name and we could just depreciate `@robinmetral/gatsby-source-s3` in favor of that. 

Dustin, you interested? 

Robin, Let me know if you have any questions.

## Tasks 

Contributor Tasks: 
- [ ] [Move Repo to `gatsby-uc`](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository#transferring-a-repository-owned-by-your-user-account)
- [ ] [Add `moonmeister` as a maintainer](https://docs.npmjs.com/transferring-a-package-from-a-user-account-to-another-user-account) on your npm package. 

Admin Tasks:
- [ ] Move Code into `gatsby-uc/plugins` repo
  - [ ] Update Readme in old repo to redirect folks to new location
  - [ ] Archive old Repo
  - [ ] Close any irrelevant PRs/Issues 
  - [ ] Move/Comment on still applicable issues
- [ ] Update Plugin with best practices
- [ ] Publish new version

**Comment by robinmetral** [comment]
Yeah definitely, otherwise we could also create something like a `@gatsby-uc` scope to put it under 🙂 

I'll look into moving the repo asap and let you know when I have questions (will probably have some around CI etc.)

**Comment by moonmeister** [comment]
Dustin got me added to `gatsby-source-s3`

**Comment by DSchau** [comment]
Hey folks 👋 

Thanks for the ping. @moonmeister DM'd me which was a great bat signal to reply and check in on this. Thank you!

Here's what I've done:

- Added @moonmeister as an owner of the gatsby-source-s3 package

Here's what I will do:

- [x] Say thank you to both ;)

Thank you!! I really appreciate you all taking the lead on this and improving the lives of Gatsby users using S3. One thing that would be really cool is a demo working on Gatsby Cloud, but totally up to you!

**Comment by DSchau** [comment]
@moonmeister you can feel free to do whatever you'd like to the README, mention it's deprecated in favor of this package, etc. etc. You have carte blanche, and I trust your judgment!

**Comment by moonmeister** [comment]
@robinmetral Would love to get this moved if you got time to [move that repo](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository#transferring-a-repository-owned-by-your-user-account) into the `gatsby-uc`.

**Comment by moonmeister** [comment]
Hey @robinmetral, I'll be talking at Gatsby Conf regarding the GUC and some of the cool plugins we are maintaining. I'd love for `gatsby-source-s3` to be apart of that.  LEt me know if you have any questions. The two actions I need from you (moving the repo and giving me npm permissions) shouldn't take more than 5 minutes. Thanks!

**Comment by robinmetral** [comment]
Hey @moonmeister, happy 2022! I'm super sorry, the past few months were crazy. I'm stoked to hear about the Gatsby Conf plans and I promise I'll get this done by EOW (at least the ownership transfer). After that I'll try to help with the e2e test setup etc., which probably won't be as straightforward to move over, but let's see 🙂

**Comment by robinmetral** [comment]
Oops, I need to have the permission to create repos in `gatsby-uc` to be able to transfer it.

I've invited you as a maintainer on the [npm package](https://www.npmjs.com/package/@robinmetral/gatsby-source-s3) 🙂

**Comment by moonmeister** [comment]
You should be able to request the transfer and I just accept it. 🤔

**Comment by moonmeister** [comment]
I've invited you to be a maintainer

**Comment by robinmetral** [comment]
Awesome! Repo moved at [gatsby-uc/gatsby-source-s3](https://github.com/gatsby-uc/gatsby-source-s3) ✅ 

Let me know if you need help for next steps. Some thoughts:

1. move the project into `gatsby-uc/plugins`
    - we'll need to figure out what to do with e2e tests here since they connect to my personal AWS account for now
    - happy to help with other things if I can, but generally the repo is pretty up-to-date already (latest `gatsby` version etc.). Feel free to get in touch  with any questions!
2. publish a new version of `gatsby-plugin-pinterest` based on `@robinmetral/gatsby-plugin-pinterest`
3. deprecate `@robinmetral/gatsby-plugin-pinterest`
    - happy to handle this part once the new `gatsby-plugin-pinterest` has been published, telling people to switch over

**Comment by moonmeister** [comment]
I'm guessing by `gatsby-source-pinterest` you mean s3?

**Comment by robinmetral** [comment]
Yes sorry 🙈 long week and many mixing plugins, I'm starting to mix them up 😄 (edited)

**Comment by moonmeister** [comment]
Okay @robinmetral for tests, do you mind if we just continue using your existing s3 buckets? if so can you DM me the needed secrets? thanks!

**Comment by robinmetral** [comment]
I think this would be fine for now, yes 🙂 let me grab new secrets with the proper access and I'll send them over DM later today

**Comment by moonmeister** [comment]
DONE!

**Comment by robinmetral** [comment]
Awesome! Thanks a lot for this 🙌 Can't wait to see the Gatsby UC grow!
