### ISSUE TITLE
add: gatsby-source-supabase

### ISSUE THREAD

**Issue by moonmeister** [gatsby-uc/plugins#181]
### Plugin Repository

alan2207/gatsby-source-supabase

### Plugin Package

package/gatsby-source-supabase

### Plugin Description

Sources data from supabase

### Tasks

Contributor Tasks: 
- [x] Move Repo to `gatsby-uc`
- [x] [Add `moonmeister` as a maintainer](https://docs.npmjs.com/transferring-a-package-from-a-user-account-to-another-user-account) on your npm package. 

Admin Tasks:
- [x] Move Code into `gatsby-uc/plugins` repo
  - [x] Update Readme in old repo to redirect folks to new location
  - [x] Archive old Repo
  - [x] Close any irrelevant PRs/Issues 
  - [x] Move/Comment on still applicable issues
- [x] Update Plugin with best practices
- [x] Publish new version

**Comment by moonmeister** [comment]
Thanks @alan2207
