### ISSUE TITLE
add gatsby-plugin-pinterest

### ISSUE THREAD

**Issue by robinmetral** [gatsby-uc/plugins#224]
### Plugin Repository

https://github.com/robinmetral/gatsby-plugin-pinterest

### Plugin Package

https://www.npmjs.com/package/gatsby-plugin-pinterest

### Plugin Description

Plugin to inject Pinterest's script at runtime. There are two main use-cases of it:

- Pinterest embeds (for example, the plugin is used under the hood by [gatsby-remark-embedder](https://github.com/MichaelDeBoey/gatsby-remark-embedder))
- Show the Pinterest "save" button on images (with options)

### Further Details

I was happy with the transfer of `gatsby-source-s3` and since I'm less involved with Gatsby in general, I'd love to transfer my other plugin. Let me know if you're happy to have it @moonmeister, and I'll be happy to help with ownership transfers, PRs or the like!

## Tasks 
**Contributor Tasks**: 
- [x] [transfer the repo](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository#transferring-a-repository-owned-by-your-user-account) to the `gatsby-uc` organization.
- [x] [Add `moonmeister` as a maintainer](https://docs.npmjs.com/transferring-a-package-from-a-user-account-to-another-user-account) on your npm package. 

**Admin Tasks:**

- [ ] Move code into `gatsby-uc/plugins` repo
  - [x] Update Readme in old repo to redirect folks to new location using [template](https://github.com/gatsby-uc/plugins/blob/main/templates/old_repo_readme.md).
  - [ ] Archive old Repo
  - [x] Close any irrelevant PRs/issues 
  - [x] Move/Comment on still applicable PRs/issues
- [ ] Update Plugin with [best practices](https://github.com/gatsby-uc/plugins/blob/main/CONTRIBUTING.md#plugin-best-practices)
- [ ] Publish new version

**Comment by moonmeister** [comment]
Hey! Yup, happy to take it. I am traveling without a computer for the summer which means I can really only review PRs. But happy to do so. Fyi, connectivity is limited so it may take me a while.

**Comment by moonmeister** [comment]
I've got some availability if we want to pick this back up.

**Comment by robinmetral** [comment]
Hey @moonmeister, sorry again for the radio silence over the past half year 🙈 notifications for this repo are back on so i (hopefully) won't miss future pings.

Let's pick this up if that's still alright with you—how do we proceed?

**Comment by moonmeister** [comment]
I'll hit you up next week

**Comment by robinmetral** [comment]
Sounds good, thanks 🙌

**Comment by moonmeister** [comment]
@robinmetral Updated the top posts with tasks. Start by transfering the repo and updating the NPM package permissions. You or I can do the Admin tasks after those are done.

**Comment by robinmetral** [comment]
@moonmeister done! 🙂
