### ISSUE TITLE
add[gatsby-plugin-ackee-tracker]

### ISSUE THREAD

**Issue by moonmeister** [gatsby-uc/plugins#54]
## Info

- Plugin Name: gatsby-plugin-ackee-tracker
- Plugin Repository: https://github.com/gatsby-uc/gatsby-plugin-ackee-tracker
- Plugin NPM page: https://www.npmjs.com/package/gatsby-plugin-ackee-tracker

## Overview

Enables Ackee Tracker in Gatsby site.

## Tasks: 

Contributor Tasks: 
- [x] Move Repo ot `gatsby-uc`
- [x] [Add `moonmeister` as a maintainer](https://docs.npmjs.com/transferring-a-package-from-a-user-account-to-another-user-account) on your npm package. 

Admin Tasks:
- [x] Move Code into `gatsby-uc/plugins` repo
  - [x] Update Readme in old repo to redirect folks to new location
  - [x] Archive old Repo
  - [x] Close any irrelevant PRs/Issues 
  - [x] Move/Comment on still applicable issues
- [x] Update Plugin with best practices
- [x] Publish new version
